import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const links = [
  {href:"/", label:"Home"},
  {href:"/docs", label:"Docs"},
  {href:"/todos", label:"Todos"},

]

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className + " py-6 px-4"}>
        <header>
          <nav className='bg-gray-400 p-6'>
              <ul className="flex items-center gap-4">
                {/* <a href="#" className=" hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium">Team</a> */}
                {links.map(link => (
                  <li key={link.href} className='text-blue-800 text-2xl hover:text-blue-600'>
                    <Link href={link.href} className="">{link.label}</Link>
                  </li>
                ))}
              </ul>
            </nav>
        </header>
        <main className='container py-6 px-6'>
          {children}
        </main>
        <footer></footer>
      </body>
    </html>
  )
}
